--- 
title: "General Social survey"
author: "Sai Prashanth Pathi, Vishwas Reddy Thuniki, Nishi Modi"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction


As a part of EDAV course final project, we would be analyzing the general social factors of United States like age, race, religion, martial status, etc. Through this analysis we aim to explain trends in American behaviors, demographics, and opinions. We want to find the wealth distribution across different race,religion and political party affiliation. Does any race, religion, etc have an advantage over others? The questions we would like to answer are listed below.

## Overview

1) How the average income change over the years?
2) Did any race show significant growth in income compared to others?
3) How does income distribute across different political party affiliation and its change over time?
4) Is there any dependency between religion and political parties affiliation?
5) Does watching more TV suggest lower income?
6) Do old people tend to watch more TV than younger people?
7) Does marital status affect the amount of time someone watches TV?
8) Does a Christianity have a bias for race and martial status ?
